version: '3'
services:
  parser:
    build: .
    image: parser:latest
    container_name: taxi-parser
    privileged: true
    volumes:
      - type: bind
        source: ./var
        target: /opt/app/var
    shm_size: '1gb'